name: num2persian
description: "A Flutter package that converts numbers into Persian letters in the easiest possible way"
version: 0.0.2
homepage: https://github.com/OmidHaqi/num2persian

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
